In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import DBSCAN
#from sklearn.preprocessing import StandardScaler
#from sklearn.preprocessing import normalize
#from sklearn.decomposition import PCA
from sklearn import metrics


In [2]:
#Importing the dataset
dataset=pd.read_csv("outputTunisianet.csv")


In [7]:
#Remplace categorical values with numeric values 0,1,2,...
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for i in dataset:
    dataset[i]=labelencoder.fit_transform(dataset[i])

In [8]:
dataset

brand  price  reference  title
0        18    391       1230    798
1        27    556        267    526
2        27    561        307    417
3        81    564       1266    693
4        27    572        266    527
...     ...    ...        ...    ...
1640     91    311       1289    343
1641     91    311       1290    352
1642     91    311       1291    408
1643     91    317       1085    380
1644     91    317       1292    346

[1645 rows x 4 columns]

In [9]:
labelencoder.inverse_transform([13])

array(['Casque Gaming  Redragon Scylla h901'], dtype=object)

In [10]:
X=dataset.iloc[::,[1,2]].values

In [12]:
X

array([[ 391, 1230],
       [ 556,  267],
       [ 561,  307],
       ...,
       [ 311, 1291],
       [ 317, 1085],
       [ 317, 1292]])

In [38]:
#Apply DBSCAN algorithm
dbscan=DBSCAN(eps=9,min_samples=5)

In [39]:
#Fitting the model
model=dbscan.fit(X)
labels=model.labels_

In [40]:
labels

array([-1, -1, -1, ..., 13, 11, 13], dtype=int64)

In [41]:
sample_cores=np.zeros_like(labels,dtype=bool)
sample_cores[dbscan.core_sample_indices_]=True

In [42]:
sample_cores

array([False, False, False, ...,  True,  True,  True])

In [43]:
#calculating the number of clusters
n_clusters=len(set(labels))-(1 if -1 in labels else 0)

In [44]:
n_clusters

56

In [45]:
print(metrics.silhouette_score(X,labels))

-0.36915577971614466
